#!/bin/bash
echo "🚀 Quick Start for DEXY with Iris"
echo "=================================="
echo ""
echo "1. Make sure Iris is running:"
echo "   - Iris indexer: npm run indexer (in iris directory)"
echo "   - Iris API: npm run api (in iris directory)"
echo ""
echo "2. Start DEXY backend:"
echo "   npm start"
echo ""
echo "3. Your frontend will automatically connect to the backend"
echo "   - Local: http://localhost:5173"
echo "   - Production: https://snekfn.vercel.app"
echo ""
echo "4. Check backend health:"
echo "   curl http://localhost:9999/api/health"
echo ""
